-- To pick the date range

AND TO_DATE(HEADER.PAID_DATE) >= NVL(TO_DATE(:P386_FROM_DATE,'MM/DD/YYYY'),TO_DATE(HEADER.PAID_DATE))
AND TO_DATE(HEADER.PAID_DATE) <= NVL(TO_DATE(:P386_TO_DATE,'MM/DD/YYYY'),TO_DATE(HEADER.PAID_DATE))

-- Query Worked For Mee

 WHERE TRUNC(DIWR.CREATED_ON) >= NVL(TO_DATE(:P15_START_DATE, 'MM-DD-YYYY'), TRUNC(DIWR.CREATED_ON))
   AND TRUNC(DIWR.CREATED_ON) <= NVL(TO_DATE(:P15_DATE_END, 'MM-DD-YYYY'), TRUNC(DIWR.CREATED_ON));

-- They both will work 
-- Make sure stored date in table matches the format you gavee
